---
- name: Put scraper program
  become: true
  copy:
    src: cgroup_memory_text_exporter.py
    dest: /usr/local/bin
    mode: 0755
- name: Put systemd timer unit
  become: true
  copy:
    src: cgroup_memory_text_exporter.timer
    dest: /etc/systemd/system
    mode: 0644
- name: Put systemd service unit
  become: true
  template:
    src: cgroup_memory_text_exporter.service
    dest: /etc/systemd/system
    mode: 0644
- name: enable systemd
  become: true
  systemd:
    daemon_reload: true
    name: cgroup_memory_text_exporter.timer
    enabled: true
    state: started
